package:
  name: m2w64-gcc
  version: 20240524

source:
  - url:
      - https://repo.msys2.org/mingw/ucrt64/mingw-w64-ucrt-x86_64-windows-default-manifest-6.4-4-any.pkg.tar.zst
      - https://github.com/conda-forge/msys2-recipes/releases/download/20240524-ucrt64/mingw-w64-ucrt-x86_64-windows-default-manifest-6.4-4-any.pkg.tar.zst
    sha256: 6d1c9e2ab75aace04d30fb43974b24d5505bfd7872ca23fea773fc9ae70bd248
    folder: binary-mingw-w64-ucrt-x86_64-windows-default-manifest

  - url:
      - https://repo.msys2.org/mingw/sources/mingw-w64-windows-default-manifest-6.4-4.src.tar.gz
      - https://github.com/conda-forge/msys2-recipes/releases/download/20240524-ucrt64/mingw-w64-windows-default-manifest-6.4-4.src.tar.gz
    sha256: c608729d05c85968580a5cd8442d06aad5d649b8375b3ccc2943f337b77ee322
    folder: source-mingw-w64-ucrt-x86_64-windows-default-manifest

  - url:
      - https://repo.msys2.org/mingw/ucrt64/mingw-w64-ucrt-x86_64-headers-git-11.0.0.r750.g05598db99-1-any.pkg.tar.zst
      - https://github.com/conda-forge/msys2-recipes/releases/download/20240524-ucrt64/mingw-w64-ucrt-x86_64-headers-git-11.0.0.r750.g05598db99-1-any.pkg.tar.zst
    sha256: b5f53e512ea67d93401d30b04a434a8d0b9d4b6cb9df39c6cc133655c51c6b5c
    folder: binary-mingw-w64-ucrt-x86_64-headers-git

  - url:
      - https://repo.msys2.org/mingw/sources/mingw-w64-headers-git-11.0.0.r750.g05598db99-1.src.tar.zst
      - https://github.com/conda-forge/msys2-recipes/releases/download/20240524-ucrt64/mingw-w64-headers-git-11.0.0.r750.g05598db99-1.src.tar.zst
    sha256: 394b97bd67d5949d0bc9f4996ecc29c656b2329f1c9aa8a6e3fa4664986adba4
    folder: source-mingw-w64-ucrt-x86_64-headers-git

  - url:
      - https://repo.msys2.org/mingw/ucrt64/mingw-w64-ucrt-x86_64-winpthreads-git-11.0.0.r750.g05598db99-1-any.pkg.tar.zst
      - https://github.com/conda-forge/msys2-recipes/releases/download/20240524-ucrt64/mingw-w64-ucrt-x86_64-winpthreads-git-11.0.0.r750.g05598db99-1-any.pkg.tar.zst
    sha256: 7f3d1c62b00fabadcc24fa5a317452adc898ae6cfa6504c8bb42829d3413ba37
    folder: binary-mingw-w64-ucrt-x86_64-winpthreads-git

  - url:
      - https://repo.msys2.org/mingw/sources/mingw-w64-winpthreads-git-11.0.0.r750.g05598db99-1.src.tar.zst
      - https://github.com/conda-forge/msys2-recipes/releases/download/20240524-ucrt64/mingw-w64-winpthreads-git-11.0.0.r750.g05598db99-1.src.tar.zst
    sha256: 81a8beceb1f43796ae9545ca52709b3b4d71a12d8248d03a7946acd14766db1b
    folder: source-mingw-w64-ucrt-x86_64-winpthreads-git

  - url:
      - https://repo.msys2.org/mingw/ucrt64/mingw-w64-ucrt-x86_64-libwinpthread-git-11.0.0.r750.g05598db99-1-any.pkg.tar.zst
      - https://github.com/conda-forge/msys2-recipes/releases/download/20240524-ucrt64/mingw-w64-ucrt-x86_64-libwinpthread-git-11.0.0.r750.g05598db99-1-any.pkg.tar.zst
    sha256: 10f636ed101de6e4855c64fa07c5666650b159bf4aae6c20e4f2cc9504539b0f
    folder: binary-mingw-w64-ucrt-x86_64-libwinpthread-git

  - url:
      - https://repo.msys2.org/mingw/sources/mingw-w64-winpthreads-git-11.0.0.r750.g05598db99-1.src.tar.zst
      - https://github.com/conda-forge/msys2-recipes/releases/download/20240524-ucrt64/mingw-w64-winpthreads-git-11.0.0.r750.g05598db99-1.src.tar.zst
    sha256: 81a8beceb1f43796ae9545ca52709b3b4d71a12d8248d03a7946acd14766db1b
    folder: source-mingw-w64-ucrt-x86_64-libwinpthread-git

  - url:
      - https://repo.msys2.org/mingw/ucrt64/mingw-w64-ucrt-x86_64-crt-git-11.0.0.r750.g05598db99-1-any.pkg.tar.zst
      - https://github.com/conda-forge/msys2-recipes/releases/download/20240524-ucrt64/mingw-w64-ucrt-x86_64-crt-git-11.0.0.r750.g05598db99-1-any.pkg.tar.zst
    sha256: 990891149df1725446c598d3aceabe286ed7edf5b8bf8957ffff7af827e2d412
    folder: binary-mingw-w64-ucrt-x86_64-crt-git

  - url:
      - https://repo.msys2.org/mingw/sources/mingw-w64-crt-git-11.0.0.r750.g05598db99-1.src.tar.zst
      - https://github.com/conda-forge/msys2-recipes/releases/download/20240524-ucrt64/mingw-w64-crt-git-11.0.0.r750.g05598db99-1.src.tar.zst
    sha256: 3563e4c579d641140efd1b49acb077e80d182ac9574cdb160eed80a9a35daa64
    folder: source-mingw-w64-ucrt-x86_64-crt-git

build:
  number: 4
  error_overlinking: false

outputs:
  - name: mingw-w64-ucrt-x86_64-windows-default-manifest
    version: 6.4.4
    script: install_pkg.bat  # [build_platform.startswith("win-")]
    script: install_pkg.sh   # [not build_platform.startswith("win-")]
    build:
      noarch: generic
    requirements:
      host:

      run:
        - __unix   # [unix]
        - __win    # [win]

    about:
      home: https://cygwin.com/
      license: BSD
      summary: |
        Default Windows application manifest (mingw-w64)

  - name: mingw-w64-ucrt-x86_64-headers-git
    version: 11.0.0.r750.g05598db99.1
    script: install_pkg.bat  # [build_platform.startswith("win-")]
    script: install_pkg.sh   # [not build_platform.startswith("win-")]
    build:
      noarch: generic
    requirements:
      host:

      run:
        - __unix   # [unix]
        - __win    # [win]

    about:
      home: https://www.mingw-w64.org/
      license: ZPL-2.1 AND LGPL-2.1-or-later
      summary: |
        MinGW-w64 headers for Windows (mingw-w64)

  - name: mingw-w64-ucrt-x86_64-winpthreads-git
    version: 11.0.0.r750.g05598db99.1
    script: install_pkg.bat  # [build_platform.startswith("win-")]
    script: install_pkg.sh   # [not build_platform.startswith("win-")]
    build:
      noarch: generic
    requirements:
      host:
        - mingw-w64-ucrt-x86_64-crt-git
        - mingw-w64-ucrt-x86_64-libwinpthread-git =11.0.0.r750.g05598db99
      run:
        - __unix   # [unix]
        - __win    # [win]
        - mingw-w64-ucrt-x86_64-crt-git
        - mingw-w64-ucrt-x86_64-libwinpthread-git =11.0.0.r750.g05598db99
    about:
      home: https://www.mingw-w64.org/
      license: MIT AND BSD-3-Clause-Clear
      summary: |
        MinGW-w64 winpthreads library (mingw-w64)

  - name: mingw-w64-ucrt-x86_64-libwinpthread-git
    version: 11.0.0.r750.g05598db99.1
    script: install_pkg.bat  # [build_platform.startswith("win-")]
    script: install_pkg.sh   # [not build_platform.startswith("win-")]
    build:
      noarch: generic
    requirements:
      host:

      run:
        - __unix   # [unix]
        - __win    # [win]

    about:
      home: https://www.mingw-w64.org/
      license: MIT AND BSD-3-Clause-Clear
      summary: |
        MinGW-w64 winpthreads library (mingw-w64)

  - name: mingw-w64-ucrt-x86_64-crt-git
    version: 11.0.0.r750.g05598db99.1
    script: install_pkg.bat  # [build_platform.startswith("win-")]
    script: install_pkg.sh   # [not build_platform.startswith("win-")]
    build:
      noarch: generic
    requirements:
      host:
        - mingw-w64-ucrt-x86_64-headers-git
      run:
        - __unix   # [unix]
        - __win    # [win]
        - mingw-w64-ucrt-x86_64-headers-git
    about:
      home: https://www.mingw-w64.org/
      license: ZPL-2.1
      summary: |
        MinGW-w64 CRT for Windows (mingw-w64)

  - name: m2w64-sysroot_win-64
    version: 11.0.0.r750.g05598db99.1
    build:
      noarch: generic
    requirements:
      run:
        - __unix   # [unix]
        - __win    # [win]
        - mingw-w64-ucrt-x86_64-windows-default-manifest
        - mingw-w64-ucrt-x86_64-crt-git
        - mingw-w64-ucrt-x86_64-headers-git
        - mingw-w64-ucrt-x86_64-winpthreads-git
    about:
      home: https://mingw-w64.sourceforge.io/
      summary: |
        MinGW-w64 sysroot for Windows

about:
  home: https://github.com/conda-forge/m2w64-gcc-feedstock
  summary: Repackaged mingw-w64 binaries

extra:
  recipe-maintainers:
    - isuruf
