package:
  name: m2w64-gcc
  version: 20230914

source:
  - url:
      - https://repo.msys2.org/mingw/x86_64/mingw-w64-ucrt-x86_64-windows-default-manifest-6.4-4-any.pkg.tar.zst
      - https://github.com/conda-forge/msys2-recipes/releases/download/20230914-ucrt64/mingw-w64-ucrt-x86_64-windows-default-manifest-6.4-4-any.pkg.tar.zst
    sha256: 6d1c9e2ab75aace04d30fb43974b24d5505bfd7872ca23fea773fc9ae70bd248
    folder: binary-mingw-w64-ucrt-x86_64-windows-default-manifest

  - url:
      - https://repo.msys2.org/mingw/sources/mingw-w64-windows-default-manifest-6.4-4.src.tar.gz
      - https://github.com/conda-forge/msys2-recipes/releases/download/20230914-ucrt64/mingw-w64-windows-default-manifest-6.4-4.src.tar.gz
    sha256: c608729d05c85968580a5cd8442d06aad5d649b8375b3ccc2943f337b77ee322
    folder: source-mingw-w64-ucrt-x86_64-windows-default-manifest

  - url:
      - https://repo.msys2.org/mingw/x86_64/mingw-w64-ucrt-x86_64-headers-git-9.0.0.6454.b4445ee52-1-any.pkg.tar.zst
      - https://github.com/conda-forge/msys2-recipes/releases/download/20230914-ucrt64/mingw-w64-ucrt-x86_64-headers-git-9.0.0.6454.b4445ee52-1-any.pkg.tar.zst
    sha256: 90dadcaff0bd569c187264b2ed32231fe2ffb6c9b40123195e75726f812ed4c9
    folder: binary-mingw-w64-ucrt-x86_64-headers-git

  - url:
      - https://repo.msys2.org/mingw/sources/mingw-w64-headers-git-9.0.0.6454.b4445ee52-1.src.tar.gz
      - https://github.com/conda-forge/msys2-recipes/releases/download/20230914-ucrt64/mingw-w64-headers-git-9.0.0.6454.b4445ee52-1.src.tar.gz
    sha256: 179b3fada62baecea0dd35ed8e94bb939b2157e5c9fb0b60c218d938755afed8
    folder: source-mingw-w64-ucrt-x86_64-headers-git

  - url:
      - https://repo.msys2.org/mingw/x86_64/mingw-w64-ucrt-x86_64-winpthreads-git-9.0.0.6454.b4445ee52-1-any.pkg.tar.zst
      - https://github.com/conda-forge/msys2-recipes/releases/download/20230914-ucrt64/mingw-w64-ucrt-x86_64-winpthreads-git-9.0.0.6454.b4445ee52-1-any.pkg.tar.zst
    sha256: 356be3d9aab2fa5877ca1b748abd503a69ba2d5d0d404ca7be5719b5517a7cd1
    folder: binary-mingw-w64-ucrt-x86_64-winpthreads-git

  - url:
      - https://repo.msys2.org/mingw/sources/mingw-w64-winpthreads-git-9.0.0.6454.b4445ee52-1.src.tar.gz
      - https://github.com/conda-forge/msys2-recipes/releases/download/20230914-ucrt64/mingw-w64-winpthreads-git-9.0.0.6454.b4445ee52-1.src.tar.gz
    sha256: 5f4f55de73c7fddd84865a289d34fc55e0506bb19c96af0ec2a1fb0833e68534
    folder: source-mingw-w64-ucrt-x86_64-winpthreads-git

  - url:
      - https://repo.msys2.org/mingw/x86_64/mingw-w64-ucrt-x86_64-libwinpthread-git-9.0.0.6454.b4445ee52-1-any.pkg.tar.zst
      - https://github.com/conda-forge/msys2-recipes/releases/download/20230914-ucrt64/mingw-w64-ucrt-x86_64-libwinpthread-git-9.0.0.6454.b4445ee52-1-any.pkg.tar.zst
    sha256: 905db9ba4cf395e1d130903864cbf70240945b77e9d6af1cc00d343914d70fb7
    folder: binary-mingw-w64-ucrt-x86_64-libwinpthread-git

  - url:
      - https://repo.msys2.org/mingw/sources/mingw-w64-winpthreads-git-9.0.0.6454.b4445ee52-1.src.tar.gz
      - https://github.com/conda-forge/msys2-recipes/releases/download/20230914-ucrt64/mingw-w64-winpthreads-git-9.0.0.6454.b4445ee52-1.src.tar.gz
    sha256: 5f4f55de73c7fddd84865a289d34fc55e0506bb19c96af0ec2a1fb0833e68534
    folder: source-mingw-w64-ucrt-x86_64-libwinpthread-git

  - url:
      - https://repo.msys2.org/mingw/x86_64/mingw-w64-ucrt-x86_64-crt-git-9.0.0.6454.b4445ee52-1-any.pkg.tar.zst
      - https://github.com/conda-forge/msys2-recipes/releases/download/20230914-ucrt64/mingw-w64-ucrt-x86_64-crt-git-9.0.0.6454.b4445ee52-1-any.pkg.tar.zst
    sha256: b20b8e3c87a43eea46548effe6277add333c40cc5303427e1cf6341e61b84436
    folder: binary-mingw-w64-ucrt-x86_64-crt-git

  - url:
      - https://repo.msys2.org/mingw/sources/mingw-w64-crt-git-9.0.0.6454.b4445ee52-1.src.tar.gz
      - https://github.com/conda-forge/msys2-recipes/releases/download/20230914-ucrt64/mingw-w64-crt-git-9.0.0.6454.b4445ee52-1.src.tar.gz
    sha256: 136cccc6534d8aa54764971cce515f753ce257486be7c18be95caeb3d97914cb
    folder: source-mingw-w64-ucrt-x86_64-crt-git

build:
  number: 4
  error_overlinking: false

outputs:
  - name: mingw-w64-ucrt-x86_64-windows-default-manifest
    version: 6.4.4
    script: install_pkg.bat  # [build_platform.startswith("win-")]
    script: install_pkg.sh   # [not build_platform.startswith("win-")]
    build:
      noarch: generic
    requirements:
      host:

      run:
        - __unix   # [unix]
        - __win    # [win]

    about:
      home: https://cygwin.com/
      license: BSD
      summary: |
        Default Windows application manifest (mingw-w64)

  - name: mingw-w64-ucrt-x86_64-headers-git
    version: 9.0.0.6454.b4445ee52.1
    script: install_pkg.bat  # [build_platform.startswith("win-")]
    script: install_pkg.sh   # [not build_platform.startswith("win-")]
    build:
      noarch: generic
    requirements:
      host:

      run:
        - __unix   # [unix]
        - __win    # [win]

    about:
      home: https://mingw-w64.sourceforge.io/
      license: custom
      summary: |
        MinGW-w64 headers for Windows

  - name: mingw-w64-ucrt-x86_64-winpthreads-git
    version: 9.0.0.6454.b4445ee52.1
    script: install_pkg.bat  # [build_platform.startswith("win-")]
    script: install_pkg.sh   # [not build_platform.startswith("win-")]
    build:
      noarch: generic
    requirements:
      host:
        - mingw-w64-ucrt-x86_64-crt-git
        - mingw-w64-ucrt-x86_64-libwinpthread-git =9.0.0.6454.b4445ee52
      run:
        - __unix   # [unix]
        - __win    # [win]
        - mingw-w64-ucrt-x86_64-crt-git
        - mingw-w64-ucrt-x86_64-libwinpthread-git =9.0.0.6454.b4445ee52
    about:
      home: https://mingw-w64.sourceforge.io/
      license: MIT
      summary: |
        MinGW-w64 winpthreads library

  - name: mingw-w64-ucrt-x86_64-libwinpthread-git
    version: 9.0.0.6454.b4445ee52.1
    script: install_pkg.bat  # [build_platform.startswith("win-")]
    script: install_pkg.sh   # [not build_platform.startswith("win-")]
    build:
      noarch: generic
    requirements:
      host:

      run:
        - __unix   # [unix]
        - __win    # [win]

    about:
      home: https://mingw-w64.sourceforge.io/
      license: MIT
      summary: |
        MinGW-w64 winpthreads library

  - name: mingw-w64-ucrt-x86_64-crt-git
    version: 9.0.0.6454.b4445ee52.1
    script: install_pkg.bat  # [build_platform.startswith("win-")]
    script: install_pkg.sh   # [not build_platform.startswith("win-")]
    build:
      noarch: generic
    requirements:
      host:
        - mingw-w64-ucrt-x86_64-headers-git
      run:
        - __unix   # [unix]
        - __win    # [win]
        - mingw-w64-ucrt-x86_64-headers-git
    about:
      home: https://mingw-w64.sourceforge.io/
      license: custom
      summary: |
        MinGW-w64 CRT for Windows

  - name: m2w64-sysroot_win-64
    version: 9.0.0.6454.b4445ee52.1
    build:
      noarch: generic
    requirements:
      run:
        - __unix   # [unix]
        - __win    # [win]
        - mingw-w64-ucrt-x86_64-windows-default-manifest
        - mingw-w64-ucrt-x86_64-crt-git
        - mingw-w64-ucrt-x86_64-headers-git
        - mingw-w64-ucrt-x86_64-winpthreads-git
    about:
      home: https://mingw-w64.sourceforge.io/
      summary: |
        MinGW-w64 sysroot for Windows

about:
  home: https://github.com/conda-forge/m2w64-gcc-feedstock
  summary: Repackaged mingw-w64 binaries

extra:
  recipe-maintainers:
    - isuruf
